name: Render video
on:
  push
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: flipword-trailer.mp4
          path: flipword-trailer.mp4
